GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Noong Ako'y Bata Pa",
  "author": "Sarah Q.",
  "url": "http://localhost:3003/api/blogs",
  "likes": 0
}

###

DELETE http://localhost:3003/api/blogs/60c6fc37e016502d9c99e7bb

### 

PUT http://localhost:3003/api/blogs/60c6fc37e016502d9c99e7bb
Content-Type: application/json

{
  "likes": 200
}
