GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhcmFoIiwiaWQiOiI2MGM5ODdjZDU1NDk5NTJiMjAwOGYzZTIiLCJpYXQiOjE2MjU4MjkwNDYsImV4cCI6MTYyNTgzMjY0Nn0.-IF6XhFh0SzTHAGR8BssuzG13MBTUiHv-x_PjypSsY4

{
  "title": "lolol3",
  "author": "Sarah Q.",
  "url": "http://localhost:3003/api/blogs",
  "likes": 2
}

###

PUT http://localhost:3003/api/blogs/60d17e8e04dcf920b42f02ba/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhcmFoIiwiaWQiOiI2MGM5ODdjZDU1NDk5NTJiMjAwOGYzZTIiLCJpYXQiOjE2MjU4NTk4NjksImV4cCI6MTYyNTg2MzQ2OX0.4JDW5f8QaFWr1QAr4OYTUxXEc4sgIR_Zrl8RYydvr5k

{
  "comment": "ang ganda naman puh neto user"
}

###

DELETE http://localhost:3003/api/blogs/60c9b8339dd9e2486046e147
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhcmFoIiwiaWQiOiI2MGM5ODdjZDU1NDk5NTJiMjAwOGYzZTIiLCJpYXQiOjE2MjM4MzM0NjEsImV4cCI6MTYyMzgzNzA2MX0.K6FBg053iDlG8UhDnCAbdDoAtJYlHsKuCqqSQVoA8M0

### 

PUT http://localhost:3003/api/blogs/60c6fc37e016502d9c99e7bb
Content-Type: application/json

{
  "likes": 200
}
