GET http://localhost:3003/api/users/

###

POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "notes": [],
    "username": "sarah",
    "name": "Sarah",
    "password": "sarah"
}

