GET http://localhost:3003/api/users/

###

POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "gemry",
    "name": "Gemry B.",
    "password": "gemry"
}

###

POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "",
    "name": "Sarah",
    "password": "sarah"
}

###

POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "sarah2",
    "name": "Sarah",
    "password": "s"
}

